<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-02-28T12:15:55 IST" name="Suite" finished-at="2024-02-28T12:16:05 IST" duration-ms="10457">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationsTest.submitOrder()[pri:0, instance:Sel.Tests.ErrorValidationsTest@4b1d6571]" name="submitOrder" class="Sel.Tests.ErrorValidationsTest"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="SubmitOrderTest.submitOrder(java.util.HashMap)[pri:0, instance:Sel.Tests.SubmitOrderTest@53f6fd09]" name="submitOrder" class="Sel.Tests.SubmitOrderTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2024-02-28T12:15:55 IST" name="Error Validations Test" finished-at="2024-02-28T12:16:05 IST" duration-ms="10457">
      <class name="Sel.Tests.ErrorValidationsTest">
        <test-method signature="submitOrder()[pri:0, instance:Sel.Tests.ErrorValidationsTest@4b1d6571]" started-at="2024-02-28T12:15:55 IST" name="submitOrder" finished-at="2024-02-28T12:16:05 IST" duration-ms="10114" status="FAIL">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Couldn't find a constructor in class com.sun.net.httpserver.Authenticator$Retry]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Couldn't find a constructor in class com.sun.net.httpserver.Authenticator$Retry
at org.testng.internal.objects.InstanceCreator.newInstance(InstanceCreator.java:57)
at org.testng.ITestObjectFactory.newInstance(ITestObjectFactory.java:10)
at org.testng.internal.objects.SimpleObjectDispenser.dispense(SimpleObjectDispenser.java:60)
at org.testng.internal.objects.GuiceBasedObjectDispenser.dispense(GuiceBasedObjectDispenser.java:28)
at org.testng.internal.BaseTestMethod.computeRetryAnalyzerInstanceToUse(BaseTestMethod.java:848)
at org.testng.internal.BaseTestMethod.getRetryAnalyzerConsideringMethodParameters(BaseTestMethod.java:816)
at org.testng.internal.BaseTestMethod.getRetryAnalyzer(BaseTestMethod.java:680)
at org.testng.internal.invokers.TestInvoker.shouldRetryTestMethod(TestInvoker.java:550)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:726)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:Sel.Tests.ErrorValidationsTest@4b1d6571]" started-at="2024-02-28T12:15:55 IST" name="launchApp" finished-at="2024-02-28T12:16:05 IST" duration-ms="10074" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
      </class> <!-- Sel.Tests.ErrorValidationsTest -->
    </test> <!-- Error Validations Test -->
  </suite> <!-- Suite -->
</testng-results>
